name: "Test with Pytest"

description: "Checkout Code, Setup Python, Install Dependencies and run Pytest"

inputs:
  dependencies-directory:
    description: Where to search for requirements files.
    required: false
    default: "."
    type: string

  tests-directory:
    description: What folder to search for requirements.
    required: true
    type: string

  module-directory:
    description: What module to test.
    required: true
    type: string

  extra-arguments:
    description: Additonal args to pass to pytest.
    required: false
    type: string

  ignore-errors:
    description: Whether to continue on error.
    required: false
    default: false
    type: boolean

  execution-report:
    description: Path to save execution report.
    required: false
    default: xunit-result
    type: string
  coverage-report:
    description: Path to save coverage report.
    required: false
    default: coverage
    type: string

runs:
  using: "composite"
  steps:
    - name: Load Cache & Dependencies
      uses: TeiaLabs/python-dependencies-action@master
      with:
        dependencies-directory: ${{ inputs.dependencies-directory }}
        application: true
        test: true

    - name: Test Module
      continue-on-error: ${{ inputs.ignore-errors == 'true' }}
      run: >
        pytest ${{ inputs.module-directory }}
        --cov=${{ inputs.module-directory }}
        --cov-report xml:${{ inputs.coverage-report }} 
        --junitxml=${{ inputs.execution-report }} 
        ${{ inputs.extra-arguments }}
      working-directory: ${{ inputs.tests-directory }}
      shell: bash

    - name: Upload pytest execution results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-exec-results
        path: ${{ inputs.tests-directory }}/${{ inputs.execution-report }}.xml

    - name: Upload pytest coverage results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-cov-results
        path: ${{ inputs.tests-directory }}/${{ inputs.coverage-report }}.xml
